name: 'MQL4 Compiler'
description: 'Compiles MQL4 programs'
author: 'xefino'

inputs:
  path:
    description: 'Path to files that should be compiled'
    required: true
  includes:
    description: 'Path of include files'
    required: false
  version:
    description: 'MetaTrader 4 platform version to use'
    required: true
  log-file:
    description: 'Log filename for compilation messages.'
    required: false
    default: 'results.log'
  syntax-only:
    description: 'Whether to check for syntax only (no binary file is generated)'
    required: false
    default: false
  verbose:
    description: 'Enables verbose mode (to print more messages)'
    required: false
    default: false

runs:
  using: composite
  steps:
  - name: Run Compiler
    shell: powershell
    run: |
      $switchParam = if ('${{ inputs.includes }}') { '${{ inputs.includes }}' } else { '.' }
      if ('${{ inputs.verbose }}') {
        ${{ github.action_path }}\entrypoint.ps1 -Files '${{ inputs.path }}' -Includes $switchParam -Version '${{ inputs.version }}' -LogFile '${{ inputs.log-file }}' -SyntaxOnly '${{ inputs.syntax-only }}' -Verbose
      } else {
        ${{ github.action_path }}\entrypoint.ps1 -Files '${{ inputs.path }}' -Includes $switchParam -Version '${{ inputs.version }}' -LogFile '${{ inputs.log-file }}' -SyntaxOnly '${{ inputs.syntax-only }}'
      }
 
branding:
  icon: 'bar-chart'
  color: 'blue'